"""Add is_in_stock column to schema

Revision ID: e0ed3ef2688a
Revises: c9763c50b737
Create Date: 2023-09-04 14:59:30.785259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ed3ef2688a'
down_revision = 'c9763c50b737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_in_stock', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_column('is_in_stock')

    # ### end Alembic commands ###
